version: '3'
services:
  nginx:
    image: docker-challenge-solved-noor-afazal #this image is committed to mkassain docker challenge repo
    ports:
      - "80:80"
    networks:
      - your-network

  metrics-scraper:
    build:
      context: ./metrics-scraper 
      dockerfile: Dockerfile
    environment:
      - TARGET_HOST=nginx:80
    networks:
      - your-network

networks:
  your-network:
    driver: bridge
